num_1=int(float(input("Enter the first number:")))
num_2=int(float(input("Enter the second number:")))
def results(a,b):
    print(f"Sum:{a+b}")
    print(f"Difference:{a-b}")
    print(f"Multiply:{a*b}")
    print(f"Division:{a/b}")
    print(f"Modulus:{a%b}")
    print(f"Int division:{a//b}")
    print(f"Power:{a**b}")
results(num_1, num_2)